### ISSUE TITLE
Congrats and a suggestion

### ISSUE THREAD

**Issue by scottjohnstone** [apirker/eShoppingSimple#3]
Hi Alexander - great work on this project!  The tie-in of holistic DDD and the applicability of microservices, in addition to the ability to clone and build the project without issue is absurdly fantastic.
I read the article and cloned the project...
- I assume I need to run the tests so that I can debug and observe the results (where to start?)
- Attempting to run the tests results in a failure on all tests with "No connection could be made because the target machine actively refused it." (where to go from here?)

Your article and code were a great example of integrating business needs with technical applicability; the missing piece for me was the tie-in.  I understand the business need, and the technical logic, but the example falls short of tying them together.  Please complete the missing 1%.

**Comment by apirker** [comment]
Hi Scott, thank you for the nice words, and I really appreciate. I had the feeling that the mapping from business needs into DDD and microservices is something which many devs and architects struggle with, and I hope I managed to explain it in a simple and straightforward way.

To you concrete question:
* These ones are not real tests, they are more meant to interact with the service without swagger api or similar. In order to debug, you can run a service in debug from Visual Studio, and interact with the swagger api, and set the corresponding break point in the service.
* The "tests" in the DevTools project, I assume those are the ones you are referring to, are intended to be used as a development tool to the test service accessibility. So these ones are not unit tests in the traditional sense, but more small applications which you can use to test a service. For that you need to instances of Visual Studio running, where in one you run the service, and in the other one you run the "unit test".

I hope this clarifies the issue?

**Comment by scottjohnstone** [comment]
Hi Alexander,

You are most welcome and I continue to be impressed with your thorough follow-up - my missing 1%. Yes, that completely clarifies the issue for me.  Thanks so much!
